### ISSUE TITLE
No groups displayed

### ISSUE THREAD

**Issue by ThomasSzuecs** [sillycat/confluence-space-user-management#11]
Hi,

we have a scenario that our confluence installation connects to AD using LDAP. There, we configured as mode read-only with local groups, which means that users come through LDAP and all groups and group assignments are local. I was hoping for that the plugin would be working, since everything is local within Confluence. Unfortunately, it displays an empty tab for where the mangable groups are displayed for space admins.

Can you confirm that thIs is related to the read-only with local groups mode?

Many thanks & best regards,
Thomas

**Comment by javahollic** [comment]
tracked as https://thepluginpeople.atlassian.net/browse/CSUM-12
