### ISSUE TITLE
List all users, provide option to tick to add to groups

### ISSUE THREAD

**Issue by mrjcleaver** [sillycat/confluence-space-user-management#12]
Looking up usernames is a pain.

I'd like a way to cross-tabulate users against the available groups, such that I can tick each user to add and remove them to groups.

| Full Name | username | group 1 | group 2 | group 3 |
| --- | --- | --- | --- | --- |
| Martin Cleaver | mrjcleaver | [ ] | [ x ] | [ x ] |

Thanks, M.

**Comment by javahollic** [comment]
Hi Martin,
We've taken over CSUM now.  I think what you describe was implemented as the Bulk Change Tool, where usernames can be typed, for auto adding to checked groups.  The current entry of usernames as text will be improved via https://thepluginpeople.atlassian.net/browse/CSUM-5

Anyway, if you checkout the latest 2.5.0 version for C6 (awaiting approval), let us know if you think anything can still be improved:  https://thepluginpeople.atlassian.net/browse/CSUM

This tracker is history :)
