### ISSUE TITLE
Plugin does not list all users - only limits to listing 30 randomly?

### ISSUE THREAD

**Issue by rebagwel** [sillycat/confluence-space-user-management#14]
We are using a COTS setup that includes Confluence and the use of the Custom Space User Management plugin. We trained up our space admins in the use of the plugin, and away things went. 

Now we are discovering that there seems to be a limitation to the listing of the members within a space group. You can add as many users as you want to a space group (for example, 100), however, the plugin only allows an admin to view up to 30 total, and it seems that the 30 is random each time.

Also, when it comes to naming space groups,  we are finding, for example, adding a group "VCF" results in a 'errorHtml', but when attempting to add "VCF-0", this is successful. However, it shows in the Permissions as 'Group Not Found' (even after a half hour, a day, a week). Additionally, creating group "Global WELD" was successful AND is valid under the Permissions. 

(We did also attempt to create groups with spaces , w/o spaces, w/ dashes, w/ users, w/o users, etc).

Any suggestions?

**Comment by javahollic** [comment]
no feedback, so just closing, if any action is needed, you'll need to log a report at https://thepluginpeople.atlassian.net/browse/CSUM
