### ISSUE TITLE
Bad performance with many users

### ISSUE THREAD

**Issue by scrobbleme** [sillycat/confluence-space-user-management#15]
We have a group with about 1200 users and are encountering a performance problem, when a user tries to acces the group from the space configuration screen.

The problem is, that a preceding IIS is blocking the request, when it tooks to long or whatever (IIS error messages are not sooo nice). 

It would be better, if the plugin really only loads the first X users, for instance 100, to show  a good paging. I don't think it is crucial to know how many users are in the group exactly.

Confluence Version: 5.1.5
Plugin Version: 2.2.1.2

**Comment by csauvanet** [comment]
Hello,

I know the project is not active lately, but I have the same issue. With a big group (more than 1000 users in it), clicking on the {host}/customspacemgmt/permissions/docustompermissionsmanage.action?key={KEY}&selectedGroup={GPE} link is too long.

After few investigation, using confluence profiling option and Thread Dumps, I can see that for any request of previous/next page the following method is called twice:

```java
csum.confluence.permissionmgmt.util.paging.LazyLoadingUserByUsernamePager#getCurrentPage()
```

It is called twice and it is fetching the whole list of users each time. The profiling reports that all the time is spend on UserAccessor.getUserByName() method (subsequent call in UserAndGroupManagementService class). This is the main issue, the full data are get twice each time, which ends up with response time higher than 45seconds for the page, even if we display users only 20 by 20.

I am not able to find a (dirty or clean) bugfix so far. If you have any advice it would be welcome.

Thanks and best regards
Colin

**Comment by javahollic** [comment]
Hi all, as part of the first commercial release we have yet to resolve some performance issues that will historically exist, they will be addressed really soon as we aim to get DC compatibility within a few weeks.
https://thepluginpeople.atlassian.net/projects/CSUM/issues/CSUM-6

Work will only be tracked on our JIRA intance from this point on.
