### ISSUE TITLE
Improve Caching

### ISSUE THREAD

**Issue by scrobbleme** [sillycat/confluence-space-user-management#16]
Hi, 
Please correct me if I'm wrong with this. I'm not currently sure how this add-on caches the results. It seems to use some value within the users session. 

Wouldn't it be more efficient to use Confluence' internal cache system, so it is possible to adjust it and flush it, when necessary? (Okay, flushing is possible to some request param)

Btw. how long is the data cached?

**Comment by javahollic** [comment]
We are tracking DC compatibility and anything affecting scalability on https://thepluginpeople.atlassian.net/projects/CSUM/issues/CSUM-6 

The 2.5.0 release we ahve just made is not DC compatible for this reason, we need to do a bit more work, which will be tracked only on our JIRA.  This site is going away!
