### ISSUE TITLE
Delete Group Link should direct to a confirmation message

### ISSUE THREAD

**Issue by thomykay** [sillycat/confluence-space-user-management#17]
The "delete group link" (under the group header) deletes a group without any confirmation message. For whatever reason people copy this link, paste it somewhere and boom!

http://.../permissions/docustompermissionsmanage.action?key=xyz&adminAction=removeGroups&groups=xyz&redirect=

As this plugin should support non-technical space administrators to easily manage groups I think a confirmation message is appropriate.

**Comment by javahollic** [comment]
This is now treacked at https://thepluginpeople.atlassian.net/browse/CSUM-9
