### ISSUE TITLE
Move a Confluence Group into confluence-space-user-managment

### ISSUE THREAD

**Issue by IlijaLetic** [sillycat/confluence-space-user-management#18]
Is it possible to move a group that is created in confluence it self to the managment plugin? I tried also to move one group to another space by chanching the space ID prename of the group, but it did not work.

Regards

**Comment by garysweaver** [comment]
@IlijaLetic In addition to the naming of the groups, there is a space permission given to the group. As long as the groups are created and managed by the CSUM plugin, all is ok. If you create group outside of the plugin or create a group and want to use that group for another space, you would need to manage the permissions of that group outside of the CSUM plugin to ensure it has permission to the correct space (and not the other space if you did not intend it to continue to have permissions to the old space).
