### ISSUE TITLE
Additional dependencies included in v2.4.0 breaking other add-ons

### ISSUE THREAD

**Issue by garysweaver** [sillycat/confluence-space-user-management#22]
Attempt to fix problems caused by additional dependencies as reported in https://github.com/sillycat/confluence-space-user-management/pull/21

**Comment by garysweaver** [comment]
Released as [2.4.1](https://github.com/sillycat/confluence-space-user-management/raw/master/releases/permissionmgmt-2.4.1.jar).

**Comment by garysweaver** [comment]
Release to marketplace blocked by: https://ecosystem.atlassian.net/browse/AMKT-14764

**Comment by bduffin** [comment]
Hi Gary.  I'm experiencing problems with SOAP services due to the dependencies referenced by this issue.  I'd like to use version 2.4.1 to resolve this, but I can't view AMKT-14764 (no permission).  What is the issue there?  Should it prevent me from using version 2.4.1?

**Comment by garysweaver** [comment]
Solved in https://ecosystem.atlassian.net/browse/AMKT-15692 - 2.4.1 should be available now.
