### ISSUE TITLE
Page Focus changes when deleting users

### ISSUE THREAD

**Issue by shankacie** [sillycat/confluence-space-user-management#23]
When you delete a user from a user group that is in a later grouping (such as User 50 in the list), the page jumps back to the very first user (users 1 through 10 view). The view should remain on the same page/user (for example, User 50) when you deleted a user. It does make it difficult to maintain larger user groups; remaining on the same user will hopefully help to make this process more efficient.

**Comment by garysweaver** [comment]
@shankacle if you'd like to PR this change and can prove that it will work with very large numbers of users in groups (e.g. 10,000), that would be very helpful.

**Comment by javahollic** [comment]
Agree, we track this now at https://thepluginpeople.atlassian.net/browse/CSUM-10
