### ISSUE TITLE
Users are still shown in group after removing them

### ISSUE THREAD

**Issue by baaderst** [sillycat/confluence-space-user-management#24]
Trying to remove users from groups, the system replies with a success message, but the user is still in the group. When checking the user in the site administration, I see that he is no longer member of the group.
We are running CONF 5.5.2 and the Plugin is version 2.3.0

**Comment by garysweaver** [comment]
Stefan,

I think there may be a timing problem here. If I remember correctly we query for the member list immediately after deletion. We could potentially add a configurable delay before re-querying the Confluence API.

I'm not sure that Atlassian could guarantee that their APIs return valid results since they may have dependencies on external user repositories, depending on your setup/configuration, and neither can this plugin, so that delay might be the only option.

If you'd like to develop that fix or have a developer on staff or could contract a developer to contribute that change, it would be good, because this project is really low on development resources/time at the moment, so I couldn't give you an ETA of when this would be fixed.

Thanks,
Gary

**Comment by baaderst** [comment]
In that case the users are still shown as members of the group after days when using the Custom Space User Management Plugin. Very strange. When checking in the site admin area the users are no longer member of the groups

**Comment by baaderst** [comment]
Still the same issue: 
group created by the add on shows members which can't be removed, even the message is "successfully removed" after the try.
A look in the system admin area in users shows that the users are not member of the group. 
A look  in the system admin area in groups shows that the users are members of the group and can't be removed. Not using the add-on and not using the on-board-admin-functions of Confluence.
Even after flushing all cashes in the admin area.

**Comment by garysweaver** [comment]
@baaderst Sorry for slow response. The caching is on the CSUM plugin side is not a Confluence Admin section caching thing- the caching happens via use of Confluence API-provided pagers and its own caching. Without that caching it is slow. Hence the refresh link (not page refresh) in the CSUM plugin which users need to use to refresh, because the changes that happen to user and group data do not send events to the plugin, so we have no idea when a change happened. If we didn't cache, we wouldn't be able to page through thousands of users without significant delays.

You said that "users are still shown as members of the group after days when using the Custom Space User Management Plugin"- did you try to close the browser after days, and reconnect with a new user session in Confluence and look at it again? If you do that and you still aren't seeing changes, then there is a problem in the Confluence API or Confluence's configuration or whatever you are using for user and group management or its configuration/environment, because we use the Confluence API to pull user and group data and assume that it returns the correct data.

Hope that helps, and if it doesn't, I'll need you to do some more investigation to determine what we could be doing differently. We had requirements early on for better performance for large companies like had 30,000 users.

**Comment by baaderst** [comment]
Gary,
many thanks.
Yes, I closed my browser and even restarted my PC in the time beeing.
My colleague who is maintaining the app server and the db checked the logs
and told me that in some cases when adding a group via the Plugin
Confluence tries to add the group in the Active Directory. In other cases
the group is added normally as an internal Confluence group like expected.
Stefan

2016-05-20 16:59 GMT+02:00 Gary S. Weaver <notifications@github.com>:

> @baaderst <https://github.com/baaderst> Sorry for slow response. The
> caching is on the CSUM plugin side is not a Confluence Admin section
> caching thing- the caching happens via use of Confluence API-provided
> pagers and its own caching. Without that caching it is slow. Hence the
> refresh link (not page refresh) in the CSUM plugin which users need to use
> to refresh, because the changes that happen to user and group data do not
> send events to the plugin, so we have no idea when a change happened. If we
> didn't cache, we wouldn't be able to page through thousands of users
> without significant delays.
>
> You said that "users are still shown as members of the group after days
> when using the Custom Space User Management Plugin"- did you try to close
> the browser after days, and reconnect with a new user session in Confluence
> and look at it again? If you do that and you still aren't seeing changes,
> then there is a problem in the Confluence API or Confluence's configuration
> or whatever you are using for user and group management or its
> configuration/environment, because we use the Confluence API to pull user
> and group data and assume that it returns the correct data.
>
> Hope that helps, and if it doesn't, I'll need you to do some more
> investigation to determine what we could be doing differently. We had
> requirements early on for better performance for large companies like had
> 30,000 users.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/sillycat/confluence-space-user-management/issues/24#issuecomment-220629753>
>



-- 
Mit freundlichen Grüßen
Stefan Baader

St.-Cajetan-Str. 10
81669 München
Tel: +49 89 40 97 54
Mobiltel.: +49 152 26 71 65 55

**Comment by baaderst** [comment]
The log entry:

2016-06-30 11:15:07,734 ERROR [TP-Processor246]
[confluence.user.actions.BrowseGroupsAction] doAdd Failed to create group:
0291-spezialisten

 -- url: /confluence/admin/users/creategroup.action | userName: baaderst |
referer:
https://sba.poing.de.oce.net/confluence/admin/users/dobrowsegroups.action |
action: creategroup
com.atlassian.confluence.user.UserManagementOperationFailedException:
javax.naming.NamingException: LDAP response read timed out, timeout
used:120000ms.; remaining name 'dc=osl,dc=oce,dc=net'

2016-07-06 13:44 GMT+02:00 Baader Stefan <stefan.baader@gmail.com>:

> Gary,
> many thanks.
> Yes, I closed my browser and even restarted my PC in the time beeing.
> My colleague who is maintaining the app server and the db checked the logs
> and told me that in some cases when adding a group via the Plugin
> Confluence tries to add the group in the Active Directory. In other cases
> the group is added normally as an internal Confluence group like expected.
> Stefan
>
> 2016-05-20 16:59 GMT+02:00 Gary S. Weaver <notifications@github.com>:
>
>> @baaderst <https://github.com/baaderst> Sorry for slow response. The
>> caching is on the CSUM plugin side is not a Confluence Admin section
>> caching thing- the caching happens via use of Confluence API-provided
>> pagers and its own caching. Without that caching it is slow. Hence the
>> refresh link (not page refresh) in the CSUM plugin which users need to use
>> to refresh, because the changes that happen to user and group data do not
>> send events to the plugin, so we have no idea when a change happened. If we
>> didn't cache, we wouldn't be able to page through thousands of users
>> without significant delays.
>>
>> You said that "users are still shown as members of the group after days
>> when using the Custom Space User Management Plugin"- did you try to close
>> the browser after days, and reconnect with a new user session in Confluence
>> and look at it again? If you do that and you still aren't seeing changes,
>> then there is a problem in the Confluence API or Confluence's configuration
>> or whatever you are using for user and group management or its
>> configuration/environment, because we use the Confluence API to pull user
>> and group data and assume that it returns the correct data.
>>
>> Hope that helps, and if it doesn't, I'll need you to do some more
>> investigation to determine what we could be doing differently. We had
>> requirements early on for better performance for large companies like had
>> 30,000 users.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/sillycat/confluence-space-user-management/issues/24#issuecomment-220629753>
>>
>
>
>
> --
> Mit freundlichen Grüßen
> Stefan Baader
>
> St.-Cajetan-Str. 10
> 81669 München
> Tel: +49 89 40 97 54
> Mobiltel.: +49 152 26 71 65 55
>



-- 
Mit freundlichen Grüßen
Stefan Baader

St.-Cajetan-Str. 10
81669 München
Tel: +49 89 40 97 54
Mobiltel.: +49 152 26 71 65 55

**Comment by garysweaver** [comment]
@baaderst assuming you haven't configured the plugin to using Jira for user management, it should just use the Confluence API to create the group via:
```
com.atlassian.user.GroupManager.createGroup(group)
```

You might ask on answers.atlassian.com for reasons why com.atlassian.user.GroupManager.createGroup(group) might sometimes add to AD and other times to Confluence's user repo. If you are using local authorization and AD, perhaps it depends on the user you are logged in as- I don't know, but that's outside of the scope of this plugin.

Good luck, and let us know what you find out!

**Comment by jappenzesr** [comment]
Hi Gary, Stefan

We are experiencing the same issue. Some users cannot be removed from the group at all: Clicking on the Remove button on the Custom Space User Management page show a success message, but other than that there is no effect. The user's association to the group is not changed, the group still shows on the User overview page. 

Confluence version 5.8.18, Plugin version 2.3.0. 

Any help is appreciated. 

Thanks, 

Johannes

**Comment by baaderst** [comment]
Gary,
when I ask Atlassian for issues occuring in 3rd party add-ons I always get
the answer to ask the vendor / developer of the add-on. Atlassian is not
willed to support here. Even the are offering the add-ons on their market
place. For me this is a never-ending story.
Best regards
Stefan

2016-07-07 19:15 GMT+02:00 Gary S. Weaver <notifications@github.com>:

> @baaderst <https://github.com/baaderst> assuming you haven't configured
> the plugin to using Jira for user management, it should just use the
> Confluence API to create the group via:
>
> com.atlassian.user.GroupManager.createGroup(group)
>
> You might ask on answers.atlassian.com for reasons why com.atlassian.user.
> GroupManager.createGroup(group) might sometimes add to AD and other times
> to Confluence's user repo. If you are using local authorization and AD,
> perhaps it depends on the user you are logged in as- I don't know, but
> that's outside of the scope of this plugin.
>
> Good luck, and let us know what you find out!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sillycat/confluence-space-user-management/issues/24#issuecomment-231145839>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASaTZXFl9ExYyQZJQFXPDq4dNSSPmcplks5qTTRBgaJpZM4Ib_D6>
> .
>



-- 
Mit freundlichen Grüßen
Stefan Baader

St.-Cajetan-Str. 10
81669 München
Tel: +49 89 40 97 54
Mobiltel.: +49 152 26 71 65 55
