### ISSUE TITLE
Can this plugin be available in JIRA ?

### ISSUE THREAD

**Issue by yletexier** [sillycat/confluence-space-user-management#25]
Hello,
We are using your plugin to delegate users management to wiki space administrators

On the same model we want to delegate projects admins the management of their project's groups.
Any chance that this plugin will be availabel as a JIRA  plugin ?

**Comment by javahollic** [comment]
An idea indeed, we've logged this as https://thepluginpeople.atlassian.net/browse/CSUM-8 , ongoing work will be tracked on our JIRA site only.
