### ISSUE TITLE
Confluence 5.10

### ISSUE THREAD

**Issue by muchino** [sillycat/confluence-space-user-management#27]
Are there are plans to support Confluence 5.10?

**Comment by KevinRaney** [comment]
@garysweaver Any progress or intent to update/certify this plugin for Confluence 5.10.x?

**Comment by thorstenha** [comment]
Hi!
I am not a plugin developer, but I did the following changes to the current pom file and rebuild the plugin, seems to work just fine with Confluence 5.10

`diff -r confluence-space-user-management-master/pom.xml confluence-space-user-management-master_5_10/pom.xml
3,5c3
< <project xmlns="http://maven.apache.org/POM/4.0.0"
<          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
<          xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
---
> <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
16c14
<     <version>2.4.2-SNAPSHOT</version>
---
>     <version>2.4.2</version>
26c24
<         <confluence.version>5.9.3</confluence.version>
---
>         <confluence.version>5.10.4</confluence.version>
44,46c42,44
<         <connection>scm:svn:http://studio.plugins.atlassian.com/svn/SUSR/trunk</connection>
<         <developerConnection>scm:svn:https://studio.plugins.atlassian.com/svn/SUSR/trunk</developerConnection>
<         <url>https://studio.plugins.atlassian.com/source/browse/SUSR/trunk</url>
---
>         <connection>scm:svn:http://studio.plugins.atlassian.com/svn/SUSR/tags/permissionmgmt-2.4.2</connection>
>         <developerConnection>scm:svn:https://studio.plugins.atlassian.com/svn/SUSR/tags/permissionmgmt-2.4.2</developerConnection>
>         <url>https://studio.plugins.atlassian.com/source/browse/SUSR/tags/permissionmgmt-2.4.2</url>
430c428
<         <repository>
---
>         
>          <repository>
>             <snapshots>
>                 <enabled>true</enabled>
>             </snapshots>
>             <releases>
>                 <enabled>true</enabled>
>             </releases>
>             <id>Codehaus Mojo</id>
>             <url>http://repo1.maven.org/maven2/</url>
>         </repository>
> 
459a470,480
>         <repository>
>             <snapshots>
>                 <enabled>true</enabled>
>             </snapshots>
>             <releases>
>                 <enabled>true</enabled>
>             </releases>
>             <id>NuxeoUS</id>
>             <url>https://maven-us.nuxeo.org/nexus/content/repositories/public/</url>
>         </repository>
> 
511c532
<             <url>http://snapshots.repository.codehaus.org</url>
---
>             <url>http://repo1.maven.org/maven2/</url>
`

Under Ubuntu, just install maven, download the latest Java JDK, set JAVA_HOME to the Java directory, go to the directory with the sources
You can also download the attached file, (just rename it to jar before installing the plugin)
[permissionmgmt-2.4.2.zip](https://github.com/sillycat/confluence-space-user-management/files/458778/permissionmgmt-2.4.2.zip)

 and run mvn release:prepare you will receive an error message, cause they seem to try to checkin the changes, but you'll find the plugin jar in the "target" directory.

**Comment by baaderst** [comment]
Great plugin, one of the most useful for Confluence. Many thanks.
Since we updated to 5.10 recently I would like to be sure if the plugin is compatible and tested for that version. I see that it seems to run properly (tested on our QA system) but it would be a security policy issue to install a plugin marked as incompatible on the production system.
Can you confirm the compatibility and if yes, could you provide an update which is detected as compatible?
Many thanks so far
