### ISSUE TITLE
ldaputil missing

### ISSUE THREAD

**Issue by backstreetkiwi** [sillycat/confluence-space-user-management#28]
Hi there,
thank you for your lovely plugin. I failed to build the latest version out-of-the-box because the library com.dolby.confluence.net:ldaputil:1.0.11 was missing. It seems to have been removed from the repo. I found it here:

https://maven-us.nuxeo.org/nexus/content/repositories/public/com/dolby/confluence/net/ldaputil/1.0.11/
(Servername: "maven-us" instead of "maven")

I did not provide a patch because I'm not sure if switching the repo as a whole is your desired solution...

Cheers, Nikolaus

**Comment by javahollic** [comment]
The LDAP integration stuff seems broken, we've disabled it in 2.5.0 but will look at this in the future to allow auto-creation (within Confluence) from LDAP.

https://thepluginpeople.atlassian.net/browse/CSUM-3

This site will be going offline soon, all ongoing maintenance will be tracked through our JIRA instance.
