### ISSUE TITLE
Compatibility with Confluence Data Center

### ISSUE THREAD

**Issue by shadmansmusings** [sillycat/confluence-space-user-management#29]
Is the plugin compatible with Confluence Data Center? If not, has anyone tried using it with Data Center? We are going to be moving to DC and currently don't have a version of DC to even test with.

**Comment by jwrobert** [comment]
@shadmansmusings, we have been using it with Data Center for quite awhile now and it does work. It is not officially compatible but we have not had any issues using it on Confluence 5.8.18 Data Center.

**Comment by shadmansmusings** [comment]
Thank you, @jwrobert for the reply. That is what I was hoping someone would say.
