### ISSUE TITLE
Group created in a space can be used in other spaces, too.

### ISSUE THREAD

**Issue by JanPriebe** [sillycat/confluence-space-user-management#30]
We were expecting groups to be visible / usable only in the space where they have been set up. Now testing your PlugIn (which works perfectly on all other aspects) we find the space group also in other spaces. Is that just a configuration thing we missed or does the PlugIn work this way in general?

**Comment by javahollic** [comment]
https://thepluginpeople.atlassian.net/browse/CSUM-7
