### ISSUE TITLE
Problem with description and button, with symbols ä, ö ü. It displays ¿?⅟₂

### ISSUE THREAD

**Issue by maximilianheyne-communardo** [sillycat/confluence-space-user-management#32]
If the browser language (in any browser is set to German, the Managing of Usergroups in the Space Configuration looks like this: 
![mmq-816](https://cloud.githubusercontent.com/assets/23479297/20308714/7d060634-ab45-11e6-9a5f-efe54d9f3c5f.png)

**Comment by javahollic** [comment]
This has been resolved in version 2.5.0 for confluence 6.0.x, just submitted to marketplace for approval.

All future work will done via https://thepluginpeople.atlassian.net/projects/CSUM/
